/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 33efd3b17229f92f32173efc2e9ad735)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "ChatAgent" | "SlackAgent";
	}
	interface Env {
		AI: Ai;
		ChatAgent: DurableObjectNamespace<import("./src/server").ChatAgent>;
		SlackAgent: DurableObjectNamespace<import("./src/server").SlackAgent>;
		SLACK_BOT_TOKEN: string;
		SLACK_SIGNING_SECRET: string;
	}
}
interface Env extends Cloudflare.Env {}
