/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 44c4b54254ee86433f18cfc090eba1f9)
interface __BaseEnv_Env {
	AI: Ai;
	SlackAgent: DurableObjectNamespace<import("./src/server").SlackAgent>;
	SLACK_BOT_TOKEN: string;
	SLACK_SIGNING_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "SlackAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
