/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: b0b7abec3741a3a1590088baa865433b)
interface __BaseEnv_Env {
	AI: Ai;
	SlackAgent: DurableObjectNamespace<import("./src/server").SlackAgent>;
	MESSAGE_WORKFLOW: Workflow<Parameters<import("./src/server").MessageWorkflow['run']>[0]['payload']>;
	LIFECYCLE_WORKFLOW: Workflow<Parameters<import("./src/server").LifecycleWorkflow['run']>[0]['payload']>;
	SLACK_BOT_TOKEN: string;
	SLACK_SIGNING_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "SlackAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
